//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace asv.ASVServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="schema.pfr.ru/asv", ConfigurationName="ASVServiceReference.AuthenticationServiceSoap")]
    public interface AuthenticationServiceSoap {
        
        // CODEGEN: Generating message contract since message AutoLoginRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="schema.pfr.ru/asv/ASV.Services.AuthenticationService.AutoLogin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        asv.ASVServiceReference.AutoLoginResponse AutoLogin(asv.ASVServiceReference.AutoLoginRequest request);
        
        // CODEGEN: Generating message contract since message LoginRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="schema.pfr.ru/asv/ASV.Services.AuthenticationService.Login", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        asv.ASVServiceReference.LoginResponse Login(asv.ASVServiceReference.LoginRequest request);
        
        // CODEGEN: Generating message contract since message LogoutRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="schema.pfr.ru/asv/ASV.Services.AuthenticationService.Logout", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        asv.ASVServiceReference.LogoutResponse Logout(asv.ASVServiceReference.LogoutRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.intersystems.com/SOAPheaders")]
    public partial class CSPCHD : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="schema.pfr.ru/asv")]
    public partial class ADBSettings : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string uBPCodeField;
        
        private string uBPNameField;
        
        private string oPFRCodeField;
        
        private string clientINNField;
        
        private string clientKPPField;
        
        private string clientAccountNumberField;
        
        private string chiefAppointmentField;
        
        private string chiefNameField;
        
        private string executorAppointmentField;
        
        private string executorNameField;
        
        private string executorPhoneField;
        
        private string noticeField;
        
        private string pathTo7ZField;
        
        private string pathToBlackBoxDirField;
        
        private string pathToDocsTemplatesField;
        
        private string pathToAnalyticalTemplatesField;
        
        private string pathToTemporaryFilesField;
        
        private string itemsPrintMaxCountField;
        
        private string pathToRepaymentResolutionUploadField;
        
        private string pathToLogFilesField;
        
        private string pathToReportODTField;
        
        private string pathToReportODSField;
        
        private string pathToAnalyticalFilesField;
        
        private string pathToFKFolderField;
        
        private string pathToFKFolderCarantinField;
        
        private string pathToAccountMessageFolderField;
        
        private string pathToAccountMessFolderCarantinField;
        
        private string pathToAccountMessageFolderOutField;
        
        private string pathToBikImportFolderField;
        
        private string pathToPreferentialTariffImportFolderField;
        
        private string pathToPreferentialTariffErrorsFolderField;
        
        private string pathToAppealProcessAttachedDocumentsField;
        
        private string sMTPLoginField;
        
        private string sMTPPasswordField;
        
        private string sMTPUrlField;
        
        private string sMTPPortField;
        
        private string mailFromField;
        
        private string mailSenderField;
        
        private string cSCalculationsErrorField;
        
        private bool cSCalculationsErrorsShowField;
        
        private bool cSCalculationsErrorsShowFieldSpecified;
        
        private bool cSEnableEditOKVEDAndTariffInCS1Field;
        
        private bool cSEnableEditOKVEDAndTariffInCS1FieldSpecified;
        
        private string cSPeriodOfVoluntaryProvisionField;
        
        private bool cSIdentifyArrearsField;
        
        private bool cSIdentifyArrearsFieldSpecified;
        
        private long maxMenuHeightField;
        
        private bool maxMenuHeightFieldSpecified;
        
        private long maxDeliveriesInListField;
        
        private bool maxDeliveriesInListFieldSpecified;
        
        private string maxSendingTimeField;
        
        private bool productionCalendarEnabledField;
        
        private bool productionCalendarEnabledFieldSpecified;
        
        private long deliveryMailRankField;
        
        private bool deliveryMailRankFieldSpecified;
        
        private long deliveryMailTypeField;
        
        private bool deliveryMailTypeFieldSpecified;
        
        private long deliveryMailCtgField;
        
        private bool deliveryMailCtgFieldSpecified;
        
        private long deliveryMailDirectField;
        
        private bool deliveryMailDirectFieldSpecified;
        
        private long deliverySendCtgField;
        
        private bool deliverySendCtgFieldSpecified;
        
        private long deliveryPostMarkField;
        
        private bool deliveryPostMarkFieldSpecified;
        
        private long pUExportMaxDocumentsCountInPackField;
        
        private bool pUExportMaxDocumentsCountInPackFieldSpecified;
        
        private string pathToOrdersFolderImportFolderField;
        
        private long daysExceedForViolationByBankMessageField;
        
        private bool daysExceedForViolationByBankMessageFieldSpecified;
        
        private long daysExceedForViolationByInsurerMessageField;
        
        private bool daysExceedForViolationByInsurerMessageFieldSpecified;
        
        private string reportServerNameField;
        
        private string pathToPaymentFLField;
        
        private long daysToStoreOldReportsField;
        
        private bool daysToStoreOldReportsFieldSpecified;
        
        private long maxEmailAttachSizeField;
        
        private bool maxEmailAttachSizeFieldSpecified;
        
        private long updateMirrorReportServerTimeField;
        
        private bool updateMirrorReportServerTimeFieldSpecified;
        
        private bool allowTerritoryUserGroupCreationField;
        
        private bool allowTerritoryUserGroupCreationFieldSpecified;
        
        private string fSSPURLField;
        
        private string fSSPPasswordField;
        
        private string fSSPLoginField;
        
        private string fakeRegNumberForInterRegionalRepayField;
        
        private string oKPOField;
        
        private string pathToOutputMessageFolderField;
        
        private string pathToInputMessageFolderField;
        
        private string pathToArchiveInputMessageFolderField;
        
        private string pathToBadInputMessageFolderField;
        
        private string compilerUniqueNumberField;
        
        private string firstMessageNumberInOperationDayField;
        
        private string maxCreditOrgMessageSendingTimeField;
        
        private bool checkProductionCalendarField;
        
        private bool checkProductionCalendarFieldSpecified;
        
        private System.DateTime lastInstalationDateField;
        
        private bool lastInstalationDateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UBPCode {
            get {
                return this.uBPCodeField;
            }
            set {
                this.uBPCodeField = value;
                this.RaisePropertyChanged("UBPCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string UBPName {
            get {
                return this.uBPNameField;
            }
            set {
                this.uBPNameField = value;
                this.RaisePropertyChanged("UBPName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string OPFRCode {
            get {
                return this.oPFRCodeField;
            }
            set {
                this.oPFRCodeField = value;
                this.RaisePropertyChanged("OPFRCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ClientINN {
            get {
                return this.clientINNField;
            }
            set {
                this.clientINNField = value;
                this.RaisePropertyChanged("ClientINN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ClientKPP {
            get {
                return this.clientKPPField;
            }
            set {
                this.clientKPPField = value;
                this.RaisePropertyChanged("ClientKPP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ClientAccountNumber {
            get {
                return this.clientAccountNumberField;
            }
            set {
                this.clientAccountNumberField = value;
                this.RaisePropertyChanged("ClientAccountNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string ChiefAppointment {
            get {
                return this.chiefAppointmentField;
            }
            set {
                this.chiefAppointmentField = value;
                this.RaisePropertyChanged("ChiefAppointment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string ChiefName {
            get {
                return this.chiefNameField;
            }
            set {
                this.chiefNameField = value;
                this.RaisePropertyChanged("ChiefName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string ExecutorAppointment {
            get {
                return this.executorAppointmentField;
            }
            set {
                this.executorAppointmentField = value;
                this.RaisePropertyChanged("ExecutorAppointment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string ExecutorName {
            get {
                return this.executorNameField;
            }
            set {
                this.executorNameField = value;
                this.RaisePropertyChanged("ExecutorName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string ExecutorPhone {
            get {
                return this.executorPhoneField;
            }
            set {
                this.executorPhoneField = value;
                this.RaisePropertyChanged("ExecutorPhone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Notice {
            get {
                return this.noticeField;
            }
            set {
                this.noticeField = value;
                this.RaisePropertyChanged("Notice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string PathTo7Z {
            get {
                return this.pathTo7ZField;
            }
            set {
                this.pathTo7ZField = value;
                this.RaisePropertyChanged("PathTo7Z");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string PathToBlackBoxDir {
            get {
                return this.pathToBlackBoxDirField;
            }
            set {
                this.pathToBlackBoxDirField = value;
                this.RaisePropertyChanged("PathToBlackBoxDir");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string PathToDocsTemplates {
            get {
                return this.pathToDocsTemplatesField;
            }
            set {
                this.pathToDocsTemplatesField = value;
                this.RaisePropertyChanged("PathToDocsTemplates");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string PathToAnalyticalTemplates {
            get {
                return this.pathToAnalyticalTemplatesField;
            }
            set {
                this.pathToAnalyticalTemplatesField = value;
                this.RaisePropertyChanged("PathToAnalyticalTemplates");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string PathToTemporaryFiles {
            get {
                return this.pathToTemporaryFilesField;
            }
            set {
                this.pathToTemporaryFilesField = value;
                this.RaisePropertyChanged("PathToTemporaryFiles");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string ItemsPrintMaxCount {
            get {
                return this.itemsPrintMaxCountField;
            }
            set {
                this.itemsPrintMaxCountField = value;
                this.RaisePropertyChanged("ItemsPrintMaxCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string PathToRepaymentResolutionUpload {
            get {
                return this.pathToRepaymentResolutionUploadField;
            }
            set {
                this.pathToRepaymentResolutionUploadField = value;
                this.RaisePropertyChanged("PathToRepaymentResolutionUpload");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string PathToLogFiles {
            get {
                return this.pathToLogFilesField;
            }
            set {
                this.pathToLogFilesField = value;
                this.RaisePropertyChanged("PathToLogFiles");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string PathToReportODT {
            get {
                return this.pathToReportODTField;
            }
            set {
                this.pathToReportODTField = value;
                this.RaisePropertyChanged("PathToReportODT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string PathToReportODS {
            get {
                return this.pathToReportODSField;
            }
            set {
                this.pathToReportODSField = value;
                this.RaisePropertyChanged("PathToReportODS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string PathToAnalyticalFiles {
            get {
                return this.pathToAnalyticalFilesField;
            }
            set {
                this.pathToAnalyticalFilesField = value;
                this.RaisePropertyChanged("PathToAnalyticalFiles");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string PathToFKFolder {
            get {
                return this.pathToFKFolderField;
            }
            set {
                this.pathToFKFolderField = value;
                this.RaisePropertyChanged("PathToFKFolder");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string PathToFKFolderCarantin {
            get {
                return this.pathToFKFolderCarantinField;
            }
            set {
                this.pathToFKFolderCarantinField = value;
                this.RaisePropertyChanged("PathToFKFolderCarantin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string PathToAccountMessageFolder {
            get {
                return this.pathToAccountMessageFolderField;
            }
            set {
                this.pathToAccountMessageFolderField = value;
                this.RaisePropertyChanged("PathToAccountMessageFolder");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string PathToAccountMessFolderCarantin {
            get {
                return this.pathToAccountMessFolderCarantinField;
            }
            set {
                this.pathToAccountMessFolderCarantinField = value;
                this.RaisePropertyChanged("PathToAccountMessFolderCarantin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string PathToAccountMessageFolderOut {
            get {
                return this.pathToAccountMessageFolderOutField;
            }
            set {
                this.pathToAccountMessageFolderOutField = value;
                this.RaisePropertyChanged("PathToAccountMessageFolderOut");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string PathToBikImportFolder {
            get {
                return this.pathToBikImportFolderField;
            }
            set {
                this.pathToBikImportFolderField = value;
                this.RaisePropertyChanged("PathToBikImportFolder");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string PathToPreferentialTariffImportFolder {
            get {
                return this.pathToPreferentialTariffImportFolderField;
            }
            set {
                this.pathToPreferentialTariffImportFolderField = value;
                this.RaisePropertyChanged("PathToPreferentialTariffImportFolder");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public string PathToPreferentialTariffErrorsFolder {
            get {
                return this.pathToPreferentialTariffErrorsFolderField;
            }
            set {
                this.pathToPreferentialTariffErrorsFolderField = value;
                this.RaisePropertyChanged("PathToPreferentialTariffErrorsFolder");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public string PathToAppealProcessAttachedDocuments {
            get {
                return this.pathToAppealProcessAttachedDocumentsField;
            }
            set {
                this.pathToAppealProcessAttachedDocumentsField = value;
                this.RaisePropertyChanged("PathToAppealProcessAttachedDocuments");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public string SMTPLogin {
            get {
                return this.sMTPLoginField;
            }
            set {
                this.sMTPLoginField = value;
                this.RaisePropertyChanged("SMTPLogin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public string SMTPPassword {
            get {
                return this.sMTPPasswordField;
            }
            set {
                this.sMTPPasswordField = value;
                this.RaisePropertyChanged("SMTPPassword");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        public string SMTPUrl {
            get {
                return this.sMTPUrlField;
            }
            set {
                this.sMTPUrlField = value;
                this.RaisePropertyChanged("SMTPUrl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=35)]
        public string SMTPPort {
            get {
                return this.sMTPPortField;
            }
            set {
                this.sMTPPortField = value;
                this.RaisePropertyChanged("SMTPPort");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=36)]
        public string MailFrom {
            get {
                return this.mailFromField;
            }
            set {
                this.mailFromField = value;
                this.RaisePropertyChanged("MailFrom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=37)]
        public string MailSender {
            get {
                return this.mailSenderField;
            }
            set {
                this.mailSenderField = value;
                this.RaisePropertyChanged("MailSender");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=38)]
        public string CSCalculationsError {
            get {
                return this.cSCalculationsErrorField;
            }
            set {
                this.cSCalculationsErrorField = value;
                this.RaisePropertyChanged("CSCalculationsError");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=39)]
        public bool CSCalculationsErrorsShow {
            get {
                return this.cSCalculationsErrorsShowField;
            }
            set {
                this.cSCalculationsErrorsShowField = value;
                this.RaisePropertyChanged("CSCalculationsErrorsShow");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CSCalculationsErrorsShowSpecified {
            get {
                return this.cSCalculationsErrorsShowFieldSpecified;
            }
            set {
                this.cSCalculationsErrorsShowFieldSpecified = value;
                this.RaisePropertyChanged("CSCalculationsErrorsShowSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=40)]
        public bool CSEnableEditOKVEDAndTariffInCS1 {
            get {
                return this.cSEnableEditOKVEDAndTariffInCS1Field;
            }
            set {
                this.cSEnableEditOKVEDAndTariffInCS1Field = value;
                this.RaisePropertyChanged("CSEnableEditOKVEDAndTariffInCS1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CSEnableEditOKVEDAndTariffInCS1Specified {
            get {
                return this.cSEnableEditOKVEDAndTariffInCS1FieldSpecified;
            }
            set {
                this.cSEnableEditOKVEDAndTariffInCS1FieldSpecified = value;
                this.RaisePropertyChanged("CSEnableEditOKVEDAndTariffInCS1Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=41)]
        public string CSPeriodOfVoluntaryProvision {
            get {
                return this.cSPeriodOfVoluntaryProvisionField;
            }
            set {
                this.cSPeriodOfVoluntaryProvisionField = value;
                this.RaisePropertyChanged("CSPeriodOfVoluntaryProvision");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=42)]
        public bool CSIdentifyArrears {
            get {
                return this.cSIdentifyArrearsField;
            }
            set {
                this.cSIdentifyArrearsField = value;
                this.RaisePropertyChanged("CSIdentifyArrears");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CSIdentifyArrearsSpecified {
            get {
                return this.cSIdentifyArrearsFieldSpecified;
            }
            set {
                this.cSIdentifyArrearsFieldSpecified = value;
                this.RaisePropertyChanged("CSIdentifyArrearsSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=43)]
        public long MaxMenuHeight {
            get {
                return this.maxMenuHeightField;
            }
            set {
                this.maxMenuHeightField = value;
                this.RaisePropertyChanged("MaxMenuHeight");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MaxMenuHeightSpecified {
            get {
                return this.maxMenuHeightFieldSpecified;
            }
            set {
                this.maxMenuHeightFieldSpecified = value;
                this.RaisePropertyChanged("MaxMenuHeightSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=44)]
        public long MaxDeliveriesInList {
            get {
                return this.maxDeliveriesInListField;
            }
            set {
                this.maxDeliveriesInListField = value;
                this.RaisePropertyChanged("MaxDeliveriesInList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MaxDeliveriesInListSpecified {
            get {
                return this.maxDeliveriesInListFieldSpecified;
            }
            set {
                this.maxDeliveriesInListFieldSpecified = value;
                this.RaisePropertyChanged("MaxDeliveriesInListSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=45)]
        public string MaxSendingTime {
            get {
                return this.maxSendingTimeField;
            }
            set {
                this.maxSendingTimeField = value;
                this.RaisePropertyChanged("MaxSendingTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=46)]
        public bool ProductionCalendarEnabled {
            get {
                return this.productionCalendarEnabledField;
            }
            set {
                this.productionCalendarEnabledField = value;
                this.RaisePropertyChanged("ProductionCalendarEnabled");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ProductionCalendarEnabledSpecified {
            get {
                return this.productionCalendarEnabledFieldSpecified;
            }
            set {
                this.productionCalendarEnabledFieldSpecified = value;
                this.RaisePropertyChanged("ProductionCalendarEnabledSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=47)]
        public long DeliveryMailRank {
            get {
                return this.deliveryMailRankField;
            }
            set {
                this.deliveryMailRankField = value;
                this.RaisePropertyChanged("DeliveryMailRank");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DeliveryMailRankSpecified {
            get {
                return this.deliveryMailRankFieldSpecified;
            }
            set {
                this.deliveryMailRankFieldSpecified = value;
                this.RaisePropertyChanged("DeliveryMailRankSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=48)]
        public long DeliveryMailType {
            get {
                return this.deliveryMailTypeField;
            }
            set {
                this.deliveryMailTypeField = value;
                this.RaisePropertyChanged("DeliveryMailType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DeliveryMailTypeSpecified {
            get {
                return this.deliveryMailTypeFieldSpecified;
            }
            set {
                this.deliveryMailTypeFieldSpecified = value;
                this.RaisePropertyChanged("DeliveryMailTypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=49)]
        public long DeliveryMailCtg {
            get {
                return this.deliveryMailCtgField;
            }
            set {
                this.deliveryMailCtgField = value;
                this.RaisePropertyChanged("DeliveryMailCtg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DeliveryMailCtgSpecified {
            get {
                return this.deliveryMailCtgFieldSpecified;
            }
            set {
                this.deliveryMailCtgFieldSpecified = value;
                this.RaisePropertyChanged("DeliveryMailCtgSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=50)]
        public long DeliveryMailDirect {
            get {
                return this.deliveryMailDirectField;
            }
            set {
                this.deliveryMailDirectField = value;
                this.RaisePropertyChanged("DeliveryMailDirect");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DeliveryMailDirectSpecified {
            get {
                return this.deliveryMailDirectFieldSpecified;
            }
            set {
                this.deliveryMailDirectFieldSpecified = value;
                this.RaisePropertyChanged("DeliveryMailDirectSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=51)]
        public long DeliverySendCtg {
            get {
                return this.deliverySendCtgField;
            }
            set {
                this.deliverySendCtgField = value;
                this.RaisePropertyChanged("DeliverySendCtg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DeliverySendCtgSpecified {
            get {
                return this.deliverySendCtgFieldSpecified;
            }
            set {
                this.deliverySendCtgFieldSpecified = value;
                this.RaisePropertyChanged("DeliverySendCtgSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=52)]
        public long DeliveryPostMark {
            get {
                return this.deliveryPostMarkField;
            }
            set {
                this.deliveryPostMarkField = value;
                this.RaisePropertyChanged("DeliveryPostMark");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DeliveryPostMarkSpecified {
            get {
                return this.deliveryPostMarkFieldSpecified;
            }
            set {
                this.deliveryPostMarkFieldSpecified = value;
                this.RaisePropertyChanged("DeliveryPostMarkSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=53)]
        public long PUExportMaxDocumentsCountInPack {
            get {
                return this.pUExportMaxDocumentsCountInPackField;
            }
            set {
                this.pUExportMaxDocumentsCountInPackField = value;
                this.RaisePropertyChanged("PUExportMaxDocumentsCountInPack");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PUExportMaxDocumentsCountInPackSpecified {
            get {
                return this.pUExportMaxDocumentsCountInPackFieldSpecified;
            }
            set {
                this.pUExportMaxDocumentsCountInPackFieldSpecified = value;
                this.RaisePropertyChanged("PUExportMaxDocumentsCountInPackSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=54)]
        public string PathToOrdersFolderImportFolder {
            get {
                return this.pathToOrdersFolderImportFolderField;
            }
            set {
                this.pathToOrdersFolderImportFolderField = value;
                this.RaisePropertyChanged("PathToOrdersFolderImportFolder");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=55)]
        public long DaysExceedForViolationByBankMessage {
            get {
                return this.daysExceedForViolationByBankMessageField;
            }
            set {
                this.daysExceedForViolationByBankMessageField = value;
                this.RaisePropertyChanged("DaysExceedForViolationByBankMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DaysExceedForViolationByBankMessageSpecified {
            get {
                return this.daysExceedForViolationByBankMessageFieldSpecified;
            }
            set {
                this.daysExceedForViolationByBankMessageFieldSpecified = value;
                this.RaisePropertyChanged("DaysExceedForViolationByBankMessageSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=56)]
        public long DaysExceedForViolationByInsurerMessage {
            get {
                return this.daysExceedForViolationByInsurerMessageField;
            }
            set {
                this.daysExceedForViolationByInsurerMessageField = value;
                this.RaisePropertyChanged("DaysExceedForViolationByInsurerMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DaysExceedForViolationByInsurerMessageSpecified {
            get {
                return this.daysExceedForViolationByInsurerMessageFieldSpecified;
            }
            set {
                this.daysExceedForViolationByInsurerMessageFieldSpecified = value;
                this.RaisePropertyChanged("DaysExceedForViolationByInsurerMessageSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=57)]
        public string ReportServerName {
            get {
                return this.reportServerNameField;
            }
            set {
                this.reportServerNameField = value;
                this.RaisePropertyChanged("ReportServerName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=58)]
        public string PathToPaymentFL {
            get {
                return this.pathToPaymentFLField;
            }
            set {
                this.pathToPaymentFLField = value;
                this.RaisePropertyChanged("PathToPaymentFL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=59)]
        public long DaysToStoreOldReports {
            get {
                return this.daysToStoreOldReportsField;
            }
            set {
                this.daysToStoreOldReportsField = value;
                this.RaisePropertyChanged("DaysToStoreOldReports");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DaysToStoreOldReportsSpecified {
            get {
                return this.daysToStoreOldReportsFieldSpecified;
            }
            set {
                this.daysToStoreOldReportsFieldSpecified = value;
                this.RaisePropertyChanged("DaysToStoreOldReportsSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=60)]
        public long MaxEmailAttachSize {
            get {
                return this.maxEmailAttachSizeField;
            }
            set {
                this.maxEmailAttachSizeField = value;
                this.RaisePropertyChanged("MaxEmailAttachSize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MaxEmailAttachSizeSpecified {
            get {
                return this.maxEmailAttachSizeFieldSpecified;
            }
            set {
                this.maxEmailAttachSizeFieldSpecified = value;
                this.RaisePropertyChanged("MaxEmailAttachSizeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=61)]
        public long UpdateMirrorReportServerTime {
            get {
                return this.updateMirrorReportServerTimeField;
            }
            set {
                this.updateMirrorReportServerTimeField = value;
                this.RaisePropertyChanged("UpdateMirrorReportServerTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UpdateMirrorReportServerTimeSpecified {
            get {
                return this.updateMirrorReportServerTimeFieldSpecified;
            }
            set {
                this.updateMirrorReportServerTimeFieldSpecified = value;
                this.RaisePropertyChanged("UpdateMirrorReportServerTimeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=62)]
        public bool AllowTerritoryUserGroupCreation {
            get {
                return this.allowTerritoryUserGroupCreationField;
            }
            set {
                this.allowTerritoryUserGroupCreationField = value;
                this.RaisePropertyChanged("AllowTerritoryUserGroupCreation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AllowTerritoryUserGroupCreationSpecified {
            get {
                return this.allowTerritoryUserGroupCreationFieldSpecified;
            }
            set {
                this.allowTerritoryUserGroupCreationFieldSpecified = value;
                this.RaisePropertyChanged("AllowTerritoryUserGroupCreationSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=63)]
        public string FSSPURL {
            get {
                return this.fSSPURLField;
            }
            set {
                this.fSSPURLField = value;
                this.RaisePropertyChanged("FSSPURL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=64)]
        public string FSSPPassword {
            get {
                return this.fSSPPasswordField;
            }
            set {
                this.fSSPPasswordField = value;
                this.RaisePropertyChanged("FSSPPassword");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=65)]
        public string FSSPLogin {
            get {
                return this.fSSPLoginField;
            }
            set {
                this.fSSPLoginField = value;
                this.RaisePropertyChanged("FSSPLogin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=66)]
        public string FakeRegNumberForInterRegionalRepay {
            get {
                return this.fakeRegNumberForInterRegionalRepayField;
            }
            set {
                this.fakeRegNumberForInterRegionalRepayField = value;
                this.RaisePropertyChanged("FakeRegNumberForInterRegionalRepay");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=67)]
        public string OKPO {
            get {
                return this.oKPOField;
            }
            set {
                this.oKPOField = value;
                this.RaisePropertyChanged("OKPO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=68)]
        public string PathToOutputMessageFolder {
            get {
                return this.pathToOutputMessageFolderField;
            }
            set {
                this.pathToOutputMessageFolderField = value;
                this.RaisePropertyChanged("PathToOutputMessageFolder");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=69)]
        public string PathToInputMessageFolder {
            get {
                return this.pathToInputMessageFolderField;
            }
            set {
                this.pathToInputMessageFolderField = value;
                this.RaisePropertyChanged("PathToInputMessageFolder");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=70)]
        public string PathToArchiveInputMessageFolder {
            get {
                return this.pathToArchiveInputMessageFolderField;
            }
            set {
                this.pathToArchiveInputMessageFolderField = value;
                this.RaisePropertyChanged("PathToArchiveInputMessageFolder");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=71)]
        public string PathToBadInputMessageFolder {
            get {
                return this.pathToBadInputMessageFolderField;
            }
            set {
                this.pathToBadInputMessageFolderField = value;
                this.RaisePropertyChanged("PathToBadInputMessageFolder");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=72)]
        public string CompilerUniqueNumber {
            get {
                return this.compilerUniqueNumberField;
            }
            set {
                this.compilerUniqueNumberField = value;
                this.RaisePropertyChanged("CompilerUniqueNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=73)]
        public string FirstMessageNumberInOperationDay {
            get {
                return this.firstMessageNumberInOperationDayField;
            }
            set {
                this.firstMessageNumberInOperationDayField = value;
                this.RaisePropertyChanged("FirstMessageNumberInOperationDay");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=74)]
        public string MaxCreditOrgMessageSendingTime {
            get {
                return this.maxCreditOrgMessageSendingTimeField;
            }
            set {
                this.maxCreditOrgMessageSendingTimeField = value;
                this.RaisePropertyChanged("MaxCreditOrgMessageSendingTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=75)]
        public bool CheckProductionCalendar {
            get {
                return this.checkProductionCalendarField;
            }
            set {
                this.checkProductionCalendarField = value;
                this.RaisePropertyChanged("CheckProductionCalendar");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CheckProductionCalendarSpecified {
            get {
                return this.checkProductionCalendarFieldSpecified;
            }
            set {
                this.checkProductionCalendarFieldSpecified = value;
                this.RaisePropertyChanged("CheckProductionCalendarSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=76)]
        public System.DateTime LastInstalationDate {
            get {
                return this.lastInstalationDateField;
            }
            set {
                this.lastInstalationDateField = value;
                this.RaisePropertyChanged("LastInstalationDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LastInstalationDateSpecified {
            get {
                return this.lastInstalationDateFieldSpecified;
            }
            set {
                this.lastInstalationDateFieldSpecified = value;
                this.RaisePropertyChanged("LastInstalationDateSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="schema.pfr.ru/asv")]
    public partial class TerritorialOrgan : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string uselessIdField;
        
        private string ptksIdField;
        
        private string shortNameField;
        
        private string companyNameField;
        
        private string codeField;
        
        private string adressField;
        
        private string headNameField;
        
        private string headAppointmentField;
        
        private string phoneField;
        
        private string oKATOField;
        
        private string iNNField;
        
        private string kPPField;
        
        private string oGRNField;
        
        private string commentField;
        
        private string eMailField;
        
        private string postAddresField;
        
        private string faxField;
        
        private string executorNameField;
        
        private string executorAppointmentField;
        
        private System.DateTime registerDateField;
        
        private bool registerDateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string uselessId {
            get {
                return this.uselessIdField;
            }
            set {
                this.uselessIdField = value;
                this.RaisePropertyChanged("uselessId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ptksId {
            get {
                return this.ptksIdField;
            }
            set {
                this.ptksIdField = value;
                this.RaisePropertyChanged("ptksId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ShortName {
            get {
                return this.shortNameField;
            }
            set {
                this.shortNameField = value;
                this.RaisePropertyChanged("ShortName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string CompanyName {
            get {
                return this.companyNameField;
            }
            set {
                this.companyNameField = value;
                this.RaisePropertyChanged("CompanyName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Adress {
            get {
                return this.adressField;
            }
            set {
                this.adressField = value;
                this.RaisePropertyChanged("Adress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string HeadName {
            get {
                return this.headNameField;
            }
            set {
                this.headNameField = value;
                this.RaisePropertyChanged("HeadName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string HeadAppointment {
            get {
                return this.headAppointmentField;
            }
            set {
                this.headAppointmentField = value;
                this.RaisePropertyChanged("HeadAppointment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
                this.RaisePropertyChanged("Phone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string OKATO {
            get {
                return this.oKATOField;
            }
            set {
                this.oKATOField = value;
                this.RaisePropertyChanged("OKATO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string INN {
            get {
                return this.iNNField;
            }
            set {
                this.iNNField = value;
                this.RaisePropertyChanged("INN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string KPP {
            get {
                return this.kPPField;
            }
            set {
                this.kPPField = value;
                this.RaisePropertyChanged("KPP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string OGRN {
            get {
                return this.oGRNField;
            }
            set {
                this.oGRNField = value;
                this.RaisePropertyChanged("OGRN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
                this.RaisePropertyChanged("Comment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string EMail {
            get {
                return this.eMailField;
            }
            set {
                this.eMailField = value;
                this.RaisePropertyChanged("EMail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string PostAddres {
            get {
                return this.postAddresField;
            }
            set {
                this.postAddresField = value;
                this.RaisePropertyChanged("PostAddres");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string Fax {
            get {
                return this.faxField;
            }
            set {
                this.faxField = value;
                this.RaisePropertyChanged("Fax");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string ExecutorName {
            get {
                return this.executorNameField;
            }
            set {
                this.executorNameField = value;
                this.RaisePropertyChanged("ExecutorName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string ExecutorAppointment {
            get {
                return this.executorAppointmentField;
            }
            set {
                this.executorAppointmentField = value;
                this.RaisePropertyChanged("ExecutorAppointment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public System.DateTime RegisterDate {
            get {
                return this.registerDateField;
            }
            set {
                this.registerDateField = value;
                this.RaisePropertyChanged("RegisterDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RegisterDateSpecified {
            get {
                return this.registerDateFieldSpecified;
            }
            set {
                this.registerDateFieldSpecified = value;
                this.RaisePropertyChanged("RegisterDateSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="schema.pfr.ru/asv")]
    public partial class TerritoryDptPFR : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string uselessIdField;
        
        private string ptksIdField;
        
        private string regDivIDField;
        
        private TerritorialOrgan territorialOrganFKField;
        
        private string addressField;
        
        private string codeField;
        
        private string currentRegNumField;
        
        private string fullNameField;
        
        private string headField;
        
        private string headPostField;
        
        private bool isCurrentField;
        
        private bool isCurrentFieldSpecified;
        
        private string nameField;
        
        private string phoneField;
        
        private string regNumStartField;
        
        private string regNumEndField;
        
        private string shortNameField;
        
        private string uniqueIdField;
        
        private bool isFictionField;
        
        private bool isFictionFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string uselessId {
            get {
                return this.uselessIdField;
            }
            set {
                this.uselessIdField = value;
                this.RaisePropertyChanged("uselessId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ptksId {
            get {
                return this.ptksIdField;
            }
            set {
                this.ptksIdField = value;
                this.RaisePropertyChanged("ptksId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string RegDivID {
            get {
                return this.regDivIDField;
            }
            set {
                this.regDivIDField = value;
                this.RaisePropertyChanged("RegDivID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public TerritorialOrgan TerritorialOrganFK {
            get {
                return this.territorialOrganFKField;
            }
            set {
                this.territorialOrganFKField = value;
                this.RaisePropertyChanged("TerritorialOrganFK");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("Address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string CurrentRegNum {
            get {
                return this.currentRegNumField;
            }
            set {
                this.currentRegNumField = value;
                this.RaisePropertyChanged("CurrentRegNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string FullName {
            get {
                return this.fullNameField;
            }
            set {
                this.fullNameField = value;
                this.RaisePropertyChanged("FullName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Head {
            get {
                return this.headField;
            }
            set {
                this.headField = value;
                this.RaisePropertyChanged("Head");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string HeadPost {
            get {
                return this.headPostField;
            }
            set {
                this.headPostField = value;
                this.RaisePropertyChanged("HeadPost");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public bool IsCurrent {
            get {
                return this.isCurrentField;
            }
            set {
                this.isCurrentField = value;
                this.RaisePropertyChanged("IsCurrent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsCurrentSpecified {
            get {
                return this.isCurrentFieldSpecified;
            }
            set {
                this.isCurrentFieldSpecified = value;
                this.RaisePropertyChanged("IsCurrentSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
                this.RaisePropertyChanged("Phone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string RegNumStart {
            get {
                return this.regNumStartField;
            }
            set {
                this.regNumStartField = value;
                this.RaisePropertyChanged("RegNumStart");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string RegNumEnd {
            get {
                return this.regNumEndField;
            }
            set {
                this.regNumEndField = value;
                this.RaisePropertyChanged("RegNumEnd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string ShortName {
            get {
                return this.shortNameField;
            }
            set {
                this.shortNameField = value;
                this.RaisePropertyChanged("ShortName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string UniqueId {
            get {
                return this.uniqueIdField;
            }
            set {
                this.uniqueIdField = value;
                this.RaisePropertyChanged("UniqueId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public bool IsFiction {
            get {
                return this.isFictionField;
            }
            set {
                this.isFictionField = value;
                this.RaisePropertyChanged("IsFiction");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsFictionSpecified {
            get {
                return this.isFictionFieldSpecified;
            }
            set {
                this.isFictionFieldSpecified = value;
                this.RaisePropertyChanged("IsFictionSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="schema.pfr.ru/asv")]
    public partial class UserInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userIdField;
        
        private string userAdditionInfoIdField;
        
        private string userFullNameField;
        
        private string emailField;
        
        private string phoneNumberField;
        
        private string initialsField;
        
        private string rolesField;
        
        private string resourcesField;
        
        private string userDepartamentCodeField;
        
        private TerritoryDptPFR[] territoryDepartamentsField;
        
        private ADBSettings configField;
        
        private bool isTerritoryUserField;
        
        private bool isTerritoryUserFieldSpecified;
        
        private System.DateTime serverTimeField;
        
        private bool serverTimeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string userId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
                this.RaisePropertyChanged("userId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string userAdditionInfoId {
            get {
                return this.userAdditionInfoIdField;
            }
            set {
                this.userAdditionInfoIdField = value;
                this.RaisePropertyChanged("userAdditionInfoId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string userFullName {
            get {
                return this.userFullNameField;
            }
            set {
                this.userFullNameField = value;
                this.RaisePropertyChanged("userFullName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string PhoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
                this.RaisePropertyChanged("PhoneNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Initials {
            get {
                return this.initialsField;
            }
            set {
                this.initialsField = value;
                this.RaisePropertyChanged("Initials");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string roles {
            get {
                return this.rolesField;
            }
            set {
                this.rolesField = value;
                this.RaisePropertyChanged("roles");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string resources {
            get {
                return this.resourcesField;
            }
            set {
                this.resourcesField = value;
                this.RaisePropertyChanged("resources");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string UserDepartamentCode {
            get {
                return this.userDepartamentCodeField;
            }
            set {
                this.userDepartamentCodeField = value;
                this.RaisePropertyChanged("UserDepartamentCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=9)]
        public TerritoryDptPFR[] TerritoryDepartaments {
            get {
                return this.territoryDepartamentsField;
            }
            set {
                this.territoryDepartamentsField = value;
                this.RaisePropertyChanged("TerritoryDepartaments");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public ADBSettings Config {
            get {
                return this.configField;
            }
            set {
                this.configField = value;
                this.RaisePropertyChanged("Config");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public bool IsTerritoryUser {
            get {
                return this.isTerritoryUserField;
            }
            set {
                this.isTerritoryUserField = value;
                this.RaisePropertyChanged("IsTerritoryUser");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsTerritoryUserSpecified {
            get {
                return this.isTerritoryUserFieldSpecified;
            }
            set {
                this.isTerritoryUserFieldSpecified = value;
                this.RaisePropertyChanged("IsTerritoryUserSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public System.DateTime ServerTime {
            get {
                return this.serverTimeField;
            }
            set {
                this.serverTimeField = value;
                this.RaisePropertyChanged("ServerTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ServerTimeSpecified {
            get {
                return this.serverTimeFieldSpecified;
            }
            set {
                this.serverTimeFieldSpecified = value;
                this.RaisePropertyChanged("ServerTimeSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AutoLogin", WrapperNamespace="schema.pfr.ru/asv", IsWrapped=true)]
    public partial class AutoLoginRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.intersystems.com/SOAPheaders")]
        public asv.ASVServiceReference.CSPCHD CSPCHD;
        
        public AutoLoginRequest() {
        }
        
        public AutoLoginRequest(asv.ASVServiceReference.CSPCHD CSPCHD) {
            this.CSPCHD = CSPCHD;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AutoLoginResponse", WrapperNamespace="schema.pfr.ru/asv", IsWrapped=true)]
    public partial class AutoLoginResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.intersystems.com/SOAPheaders")]
        public asv.ASVServiceReference.CSPCHD CSPCHD;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="schema.pfr.ru/asv", Order=0)]
        public bool AutoLoginResult;
        
        public AutoLoginResponse() {
        }
        
        public AutoLoginResponse(asv.ASVServiceReference.CSPCHD CSPCHD, bool AutoLoginResult) {
            this.CSPCHD = CSPCHD;
            this.AutoLoginResult = AutoLoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Login", WrapperNamespace="schema.pfr.ru/asv", IsWrapped=true)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.intersystems.com/SOAPheaders")]
        public asv.ASVServiceReference.CSPCHD CSPCHD;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="schema.pfr.ru/asv", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="schema.pfr.ru/asv", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="schema.pfr.ru/asv", Order=2)]
        public string clientVersion;
        
        public LoginRequest() {
        }
        
        public LoginRequest(asv.ASVServiceReference.CSPCHD CSPCHD, string username, string password, string clientVersion) {
            this.CSPCHD = CSPCHD;
            this.username = username;
            this.password = password;
            this.clientVersion = clientVersion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoginResponse", WrapperNamespace="schema.pfr.ru/asv", IsWrapped=true)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.intersystems.com/SOAPheaders")]
        public asv.ASVServiceReference.CSPCHD CSPCHD;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="schema.pfr.ru/asv", Order=0)]
        public asv.ASVServiceReference.UserInfo LoginResult;
        
        public LoginResponse() {
        }
        
        public LoginResponse(asv.ASVServiceReference.CSPCHD CSPCHD, asv.ASVServiceReference.UserInfo LoginResult) {
            this.CSPCHD = CSPCHD;
            this.LoginResult = LoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Logout", WrapperNamespace="schema.pfr.ru/asv", IsWrapped=true)]
    public partial class LogoutRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.intersystems.com/SOAPheaders")]
        public asv.ASVServiceReference.CSPCHD CSPCHD;
        
        public LogoutRequest() {
        }
        
        public LogoutRequest(asv.ASVServiceReference.CSPCHD CSPCHD) {
            this.CSPCHD = CSPCHD;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LogoutResponse", WrapperNamespace="schema.pfr.ru/asv", IsWrapped=true)]
    public partial class LogoutResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.intersystems.com/SOAPheaders")]
        public asv.ASVServiceReference.CSPCHD CSPCHD;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="schema.pfr.ru/asv", Order=0)]
        public bool LogoutResult;
        
        public LogoutResponse() {
        }
        
        public LogoutResponse(asv.ASVServiceReference.CSPCHD CSPCHD, bool LogoutResult) {
            this.CSPCHD = CSPCHD;
            this.LogoutResult = LogoutResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AuthenticationServiceSoapChannel : asv.ASVServiceReference.AuthenticationServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthenticationServiceSoapClient : System.ServiceModel.ClientBase<asv.ASVServiceReference.AuthenticationServiceSoap>, asv.ASVServiceReference.AuthenticationServiceSoap {
        
        public AuthenticationServiceSoapClient() {
        }
        
        public AuthenticationServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuthenticationServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthenticationServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthenticationServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        asv.ASVServiceReference.AutoLoginResponse asv.ASVServiceReference.AuthenticationServiceSoap.AutoLogin(asv.ASVServiceReference.AutoLoginRequest request) {
            return base.Channel.AutoLogin(request);
        }
        
        public bool AutoLogin(ref asv.ASVServiceReference.CSPCHD CSPCHD) {
            asv.ASVServiceReference.AutoLoginRequest inValue = new asv.ASVServiceReference.AutoLoginRequest();
            inValue.CSPCHD = CSPCHD;
            asv.ASVServiceReference.AutoLoginResponse retVal = ((asv.ASVServiceReference.AuthenticationServiceSoap)(this)).AutoLogin(inValue);
            CSPCHD = retVal.CSPCHD;
            return retVal.AutoLoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        asv.ASVServiceReference.LoginResponse asv.ASVServiceReference.AuthenticationServiceSoap.Login(asv.ASVServiceReference.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public asv.ASVServiceReference.UserInfo Login(ref asv.ASVServiceReference.CSPCHD CSPCHD, string username, string password, string clientVersion) {
            asv.ASVServiceReference.LoginRequest inValue = new asv.ASVServiceReference.LoginRequest();
            inValue.CSPCHD = CSPCHD;
            inValue.username = username;
            inValue.password = password;
            inValue.clientVersion = clientVersion;
            asv.ASVServiceReference.LoginResponse retVal = ((asv.ASVServiceReference.AuthenticationServiceSoap)(this)).Login(inValue);
            CSPCHD = retVal.CSPCHD;
            return retVal.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        asv.ASVServiceReference.LogoutResponse asv.ASVServiceReference.AuthenticationServiceSoap.Logout(asv.ASVServiceReference.LogoutRequest request) {
            return base.Channel.Logout(request);
        }
        
        public bool Logout(ref asv.ASVServiceReference.CSPCHD CSPCHD) {
            asv.ASVServiceReference.LogoutRequest inValue = new asv.ASVServiceReference.LogoutRequest();
            inValue.CSPCHD = CSPCHD;
            asv.ASVServiceReference.LogoutResponse retVal = ((asv.ASVServiceReference.AuthenticationServiceSoap)(this)).Logout(inValue);
            CSPCHD = retVal.CSPCHD;
            return retVal.LogoutResult;
        }
    }
}
